### ISSUE TITLE
Rename repo to EasyEffects-Presets?

### ISSUE THREAD

**Issue by vchernin** [JackHack96/EasyEffects-Presets#20]
Since EasyEffects is the primary target of this repo now, I think it makes sense the repo name matches that.

GitHub lets you just rename the repo, and old links to https://github.com/JackHack96/PulseEffects-Presets will be seamlessly redirected to https://github.com/JackHack96/EasyEffects-Presets

**Comment by JackHack96** [comment]
Yeah it kinda makes sense. I didn't know about the redirect, that's cool!
