### ISSUE TITLE
Manual installation section small correction

### ISSUE THREAD

**Issue by Dynamo1986** [JackHack96/EasyEffects-Presets#23]
Love your presets!

Very small error noted in the manual installation section. Where it is written, "If you installed it through Flatpak, you can find it in `~/.var/app/com.github.wwmm.EasyEffects/config/easyeffects`," the `com.github.wwmm.EasyEffects` should be written `com.github.wwmm.easyeffects` such that the directory to seek is, `~/.var/app/com.github.wwmm.easyeffects/config/easyeffects`.

Caused a (small but forgivable) headache!

**Comment by JackHack96** [comment]
Sorry, fixed it
