### ISSUE TITLE
Cave sound with Laptop preset using Easyeffects on pipewire.

### ISSUE THREAD

**Issue by legendhiro** [JackHack96/EasyEffects-Presets#24]
Using EndeavourOS Apolo build 2022.04.08 with easyeffects installed via pacman. Had this issue with every distro I used with pipewire and easyeffects. When I select the Laptop preset the sound is like in a cave and it goes lower and lower until there is no sound at all.
Same on my desktop.
I can give more information if needed.

**Comment by JackHack96** [comment]
Weird thing, I too use pipewire and easyeffects (via Flatpak) but on Ubuntu and the only issue I have is the automatic reset of the volume to the maximum every time I change the playing track.

Anyway, this repo just hosts some presets, this issue should be opened in the official EasyEffects repo, https://github.com/wwmm/easyeffects
