### ISSUE TITLE
Bass sound slightly reduced when I installed Realtime Privileges on Arch Linux based distro (EndeavourOS)

### ISSUE THREAD

**Issue by Reno-Sifana** [JackHack96/EasyEffects-Presets#28]
Hi. In the past, when I didn't install Realtime Privileges a few months ago, the mid range sound was a bit muffled, the bass was pretty good. Now that I have installed Realtime Privileges on EndeavorOS, added a user group and restarted, the vocals are clear, but the bass sound is reduced, even less audible in some songs via the headset.
Presets I loaded: Bass Enhancer + Perfect EQ

**Comment by JackHack96** [comment]
I'm sorry but I can't help you as these are only presets.
This could be Runtime Priviliges that for some reason makes EasyEffects not working ok or many other things. You should ask in the EasyEffects repo or in the EndeavuourOS community.
