### ISSUE TITLE
Loading a preset doesn't change anything

### ISSUE THREAD

**Issue by dawidnawrot** [JackHack96/EasyEffects-Presets#29]
Question might be quite stupid or I don't know how to set it up, but once I've downloaded a json file and loaded it into pulseeffects all the categories on the left are still disabled (equalizer, crystalizer and so on). I've tried another json file from different resource and it enabled most of the categories and provided adjustments which makes sound much better. This is how it looks in my case:

![screenshot_74](https://user-images.githubusercontent.com/24315412/181936686-1eaf2ec2-5f50-47e1-84b4-508c5c5da4e6.png)

So how to set it up to hear the difference?

**Comment by JackHack96** [comment]
Hi Dawid. Well my presets just don't use very much effects, for example if you use "Perfect EQ" as I see in the picture it should enable just the Equalizer, so it's perfectly normal.

If it doesn't load anything, then it might be that you're using the old PulseEffects app for PulseAudio but newer EasyEffects presets, which I do not recommend. For that there's a specific pulseeffects branch in this repository.

**Comment by dawidnawrot** [comment]
Yep, that's the thing, it was just an old PulseEffect and probably the structure of json should be different. Thanks, I'll take a look at legacy branch. Thanks.
