### ISSUE TITLE
Laptop preset corrupt?

### ISSUE THREAD

**Issue by jonas-w** [JackHack96/EasyEffects-Presets#31]
When trying to load the preset "Laptop":
```
(easyeffects:125455): easyeffects-WARNING **: 20:43:36.091: 	lv2_wrapper.cpp:65	Could not find the plugin: urn:zamaudio:ZaMaximX2

(easyeffects:125455): easyeffects-WARNING **: 20:43:36.091: 	lv2_wrapper.cpp:353	urn:zamaudio:ZaMaximX2 port symbol not found: thresh

(easyeffects:125455): easyeffects-WARNING **: 20:43:36.091: 	lv2_wrapper.cpp:353	urn:zamaudio:ZaMaximX2 port symbol not found: ceil

(easyeffects:125455): easyeffects-WARNING **: 20:43:36.091: 	lv2_wrapper.cpp:353	urn:zamaudio:ZaMaximX2 port symbol not found: rel

(easyeffects:125455): easyeffects-WARNING **: 20:43:36.496: 	presets_manager.cpp:797	A parsing error occurred while trying to load the blocklist from the preset. The file could be invalid or corrupted. Please check its content.

(easyeffects:125455): easyeffects-WARNING **: 20:43:36.499: 	presets_manager.cpp:331	[json.exception.out_of_range.403] key 'blocklist' not found
```

**Comment by morrolinux** [comment]
same

**Comment by JackHack96** [comment]
Mmmh I didn't make that preset so I actually don't know what it uses. From the log it seems that it uses a plugin that is no longer supported or uses properties keys that have been changed.
I'll take a look at it when I have some time.

**Comment by JackHack96** [comment]
Ok I updated the URL that points to the laptop preset and now it should be compatible with EasyEffects.

**Comment by morrolinux** [comment]
Thanks!

**Comment by morrolinux** [comment]
> @morrolinux Non mi aspettavo di ricevere un commento da te, il preset laptop ha già causato problemi ad un utente, spero di non rovinare ulteriormente il tuo portatile xD

Ahah sì beh avendo le casse del thinkpad cercavo di mitigare la situazione.. causato problemi tipo rovinato gli speaker?

**Comment by JackHack96** [comment]
> 

Si, un utente mi aveva contattato lamentandosi che non gli andavano più dopo aver sparato tutto a palla, quindi ne deduco che in quel caso è stata fatta passare troppa corrente danneggiando la bobina. Però è un corner case davvero raro, tra l'altro indica che il produttore ha fatto un collegamento elettrico non buono perché non viene limitata a dovere la corrente.
