### ISSUE TITLE
I want to delete it, how can I do it?

### ISSUE THREAD

**Issue by rznkolds** [JackHack96/EasyEffects-Presets#40]
And if I want to delete it, how can I do it ?

**Comment by JackHack96** [comment]
To delete the presets you just delete the presets in the folder (or the folder directly to delete everything).
The folder can be located in:
- `$HOME/.var/app/com.github.wwmm.easyeffects/config/easyeffects`
- `$HOME/.config/easyeffects`
The first is for Flatpak installations and the second is for APT/native installations

**Comment by rznkolds** [comment]
Does this process also delete the application that comes with Easy Effect ?

**Comment by JackHack96** [comment]
No, this just deletes all the settings and presets of EasyEffects. Think of it like performing a "factory reset".
Thus the next time you start EasyEffects you'll see it like it was freshly installed.

**Comment by rznkolds** [comment]
I did exactly what you said but nothing changed, I still have a cow symbol in my menu.

**Comment by JackHack96** [comment]
A "cow" symbol? I don't know what that is I'm sorry.

This is the effect that is obtained by deleting the aforementioned folder, as you can see all the presets and settings are deleted accordingly.
![Screenshot from 2023-10-15 08-14-35](https://github.com/JackHack96/EasyEffects-Presets/assets/3611330/22a64790-9782-4006-b6fb-25c6e0b3b398)
![Screenshot from 2023-10-15 08-15-40](https://github.com/JackHack96/EasyEffects-Presets/assets/3611330/06a37438-8488-4b2f-a029-0156670f6bed)

**Comment by rznkolds** [comment]
When I loaded your presets, an icon like this started to appear on the menu :

![sender](https://github.com/JackHack96/EasyEffects-Presets/assets/97980164/1e5e62dc-c8ce-499d-866c-161f78a888f2)

This icon comes back even when I reinstall easyeffect.

**Comment by JackHack96** [comment]
Ah okay! Well that's weird, this repo contains just a bunch of presets, no apps are installed, so it should have appeared even before.

Anyway those are plugins needed by EasyEffects, they appear if you installed it through native installation (e.g. APT, AUR, etc.) while if you use Flatpak they do not appear in the app menu.
I'm not sure if you can uninstall them though as they should be a dependency of EasyEffects itself...
