### ISSUE TITLE
Add small improvements to documentation

### ISSUE THREAD

**Issue by kardwen** [JackHack96/EasyEffects-Presets#42]
Hey :)
if you want you could add that presets are stored in `~/.config/easyeffects/output` and that they can be loaded with the preset button in the upper left corner in EasyEffects and combine multiple effects and are more than simply an equalizer.
Those were the things that were unclear to me at first because I have never used EasyEffects before and maybe that would also be helpful for others!

**Comment by JackHack96** [comment]
Technically it's written here https://github.com/wwmm/easyeffects/wiki/Community-Presets

**Comment by kardwen** [comment]
Thanks, that should be sufficient
